### ISSUE TITLE
Runaway Loop Detected

### ISSUE THREAD

**Issue by Hunanbean** [studiostry/UE4MBLabCharacterStudy#10]
Hello.
In the last issue we discussed, I mentioned that the test.dat file is missing or corrupt. I prepared a new file using Preston-Blair .dat output from papagayo-ng and used your python script to convert it for use with your included model. I directed the LipSyncTool in the VoiceTest level to the newfile, which is in the same directory as the test.dat "tools\voicetool\newfile.dat". At this point i press the Lip Sync button and the process starts to write the FaceTimeData. some data is written, but after a few seconds, i get the following error:

`LogScript: Warning: Runaway loop detected (over 1,000,000 iterations) - see log for stack trace
    CommonFunctions_BP_C /Game/fBlah/Common/BP/CommonFunctions_BP.Default__CommonFunctions_BP_C
    Function /Game/fBlah/Common/BP/CommonFunctions_BP.CommonFunctions_BP_C:SplitString:02AA
PIE: Error: Infinite loop detected. Blueprint:  CommonFunctions_BP Function:  Outputs Call Stack:  Show`

I could not find any obvious reason for this.
Thank you

**Comment by fblah** [comment]
Hi,
I have renamed the test.dat file to test.txt and uploaded it here. You can rename it back once you download it.
[Test.txt](https://github.com/studiostry/UE4MBLabCharacterStudy/files/6396771/Test.txt)
If you open it in a text editor you will understand that it just contains the face expressions from papagayo save with the frame number. The file itself is tiny but it got added to LFS since it's extension is .dat

Can you ensure that the contents of your dat file exported from papagayo looks similar?

The loop runs till it reaches the end of the file while reading its contents, could the file be corrupted?

Video Tutorial for reference:
[https://www.youtube.com/watch?v=WLRngOwCVB0](https://www.youtube.com/watch?v=WLRngOwCVB0)

God Speed!

**Comment by Hunanbean** [comment]
It was user error. When constructing my custom phoneme list for the 39 viseme set, I missed reference to SH. So, i had only created 38 of the 39 references in the FaceAndVoiceManager. The BP did not like this, with good reason. My apologies

Thank you

P.s. thanks for the file, it will help with tests
